In [1]:
print("Hello world1")

Hello world1


In [2]:
list1 = range(200000)
print(list1)

range(0, 200000)


In [4]:
%time for i in range(0 , 10): [num*5 for num in list1]

CPU times: total: 312 ms
Wall time: 318 ms


In [7]:
import numpy as np

In [10]:
list2 = np.arange(200000)
%time k = list2*5

CPU times: total: 0 ns
Wall time: 8.1 ms


In [11]:
a = np.zeros(16)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
b = np.ones(17)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
type(b[0])

numpy.float64

In [15]:
b.dtype

dtype('float64')

In [27]:
c = np.empty(20)
c

array([8.35418264e-312, 8.35437153e-312, 8.35437153e-312, 8.35437153e-312,
       8.35437186e-312, 8.35437186e-312, 8.35437186e-312, 8.35437186e-312,
       8.35437186e-312, 8.35437186e-312, 8.35437186e-312, 8.35437185e-312,
       8.35437184e-312, 8.35437185e-312, 8.35437186e-312, 8.35437185e-312,
       8.35437185e-312, 8.35437185e-312, 8.35437185e-312, 8.35437185e-312])

In [28]:
c.shape = (5,4)
c

array([[8.35418264e-312, 8.35437153e-312, 8.35437153e-312,
        8.35437153e-312],
       [8.35437186e-312, 8.35437186e-312, 8.35437186e-312,
        8.35437186e-312],
       [8.35437186e-312, 8.35437186e-312, 8.35437186e-312,
        8.35437185e-312],
       [8.35437184e-312, 8.35437185e-312, 8.35437186e-312,
        8.35437185e-312],
       [8.35437185e-312, 8.35437185e-312, 8.35437185e-312,
        8.35437185e-312]])

TypeError: 'tuple' object is not callable

In [35]:
d = np.linspace(3,200 , 10)
d

array([  3.        ,  24.88888889,  46.77777778,  68.66666667,
        90.55555556, 112.44444444, 134.33333333, 156.22222222,
       178.11111111, 200.        ])

In [36]:
e = np.arange(3,200,10)
e


array([  3,  13,  23,  33,  43,  53,  63,  73,  83,  93, 103, 113, 123,
       133, 143, 153, 163, 173, 183, 193])

In [38]:
f = np.array(10,20)
f

TypeError: Cannot interpret '20' as a data type