In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [3]:
print(np.dot(x,y))

32


In [4]:
np.dot(y,x)

32

In [8]:
a = np.array([[1,2,3],
             [4,5,6]])

In [9]:
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
np.dot(a,x)

array([14, 32])

In [11]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
b = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [19]:
inv_b = np.linalg.inv(b)

In [20]:
inv_b

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [21]:
np.dot(b,inv_b)

array([[ 0.,  0.,  0.],
       [-4.,  0., -4.],
       [ 0.,  0.,  0.]])

In [22]:
b@inv_b

array([[ 0.,  0.,  0.],
       [-4.,  0., -4.],
       [ 0.,  0.,  0.]])

In [23]:
d =np.array([[3,4],[5,6]])

In [24]:
d

array([[3, 4],
       [5, 6]])

In [25]:
np.linalg.det(d)

-2.0000000000000013

In [26]:
np.trace(d)

9

In [28]:
e = np.array([[1,2],[3,4]])

In [31]:
np.trace(e)

5