In [2]:
import numpy as np

In [3]:
A = np.array([1,2,3,4,5,6,7,8,9,10])
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
A.mean()

5.5

In [6]:
A.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [7]:
A.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

In [8]:
A.sum()

55

In [9]:
A>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [10]:
A.any()

True

In [11]:
A.all()

True

In [13]:
B = A

In [14]:
B.all()

True

In [19]:
c = np.array([2,4,6,1,7,98,92,22,35,97,21,43])

In [20]:
c

array([ 2,  4,  6,  1,  7, 98, 92, 22, 35, 97, 21, 43])

In [21]:
c.sort()

In [22]:
print(c)

[ 1  2  4  6  7 21 22 35 43 92 97 98]


In [23]:
d = np.array([1,1,2,3,4,4,5,6,6,7,7,7,4,])

In [24]:
np.unique(d)

array([1, 2, 3, 4, 5, 6, 7])